=== olmozavala/OWGIS/src/main/webapp/layers/schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="MenuConf"><!-- root element-->
  
		<xs:complexType mixed="true">
			<xs:sequence maxOccurs="unbounded"><!--childs of root, limited to 3 for now -->    
   
				<xs:element name="Menus" minOccurs="0"><!--Menus(root's child) level -->
					<xs:complexType mixed="true">
  
						<xs:sequence maxOccurs="unbounded"><!--infinite limit of MenuEntry numbers -->
      
							<xs:element name="MenuEntry" minOccurs="1"> <!--MenuEntry level -->
								<xs:complexType mixed="true">          
									<xs:attribute name="ID" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="EN" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="ES" type="xs:string" ></xs:attribute>
									<xs:attribute name="FR" type="xs:string" ></xs:attribute>
									<xs:attribute name="MS" type="xs:string" ></xs:attribute>
									<xs:attribute name="PT" type="xs:string" ></xs:attribute>
									<xs:attribute name="BN" type="xs:string" ></xs:attribute>
									<xs:attribute name="AR" type="xs:string" ></xs:attribute>
									<xs:attribute name="RU" type="xs:string" ></xs:attribute>
									<xs:attribute name="HI_IN" type="xs:string" ></xs:attribute>
									<!-- For validating other languages is necessary to add them here -->
								</xs:complexType>                 
							</xs:element>       
						</xs:sequence>  
					</xs:complexType>
				</xs:element><!--end of Menus -->
   
				<xs:element name="BackgroundLayers" minOccurs="0"> <!--BackgroundLayers (root's child) level -->
       
					<xs:complexType mixed="true">
						<!--different optional atributes of background layer -->
       
						<xs:sequence maxOccurs="unbounded">
       
							<xs:element name="layer" minOccurs="1"> <!--Menuconf/BackgroundLayers/layer -->
								<xs:complexType mixed="true">
          
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string" />
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="style" type="xs:string" /> 
								</xs:complexType>
                  
							</xs:element><!-- End of Menuconf/BackgroundLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of BackgroundLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      

						<xs:attribute name="style" type="xs:string" />  
					</xs:complexType>
				</xs:element> <!--End of BackgroundLayer -->
   
				<xs:element name="OptionalLayers" minOccurs="0"> <!--OptionalLayers (root's child) level -->
       
					<xs:complexType mixed="true">
						<xs:sequence maxOccurs="unbounded">
       
							<xs:element name="layer" minOccurs="1"> <!--Menuconf/BackgroundLayers/layer -->
								<xs:complexType mixed="true">
          
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="Menu" type="xs:string"></xs:attribute>
									<xs:attribute name="featureInfo" type="xs:string"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string" />
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="selected">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      

									<xs:attribute name="style" type="xs:string" /> 
								</xs:complexType>
                  
							</xs:element><!-- End of Menuconf/OptionalLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of OptionalLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      

						<xs:attribute name="style" type="xs:string" />
                        <xs:attribute name="zoom" type="xs:string" />
                        <xs:attribute name="center" type="xs:string" />  
					</xs:complexType>
				</xs:element> <!--End of OptionalLayers -->
   
   
				<xs:element name="MainLayers" minOccurs="0"> <!--MainLayers (root's child) level -->
					<xs:complexType mixed="true">
						<xs:sequence maxOccurs="unbounded"><!-- There can be multiple MainLayers element on the xml file -->
							<xs:element name="layer" minOccurs="1"> <!--Internal element of Main layers is a layer -->
								<xs:complexType mixed="true">
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="Menu" type="xs:string"></xs:attribute>
									<xs:attribute name="featureInfo" type="xs:string"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="EN" type="xs:string"></xs:attribute>
									<xs:attribute name="ES" type="xs:string" ></xs:attribute>
									<xs:attribute name="FR" type="xs:string" ></xs:attribute>
									<xs:attribute name="MS" type="xs:string" ></xs:attribute>
									<xs:attribute name="PT" type="xs:string" ></xs:attribute>
									<xs:attribute name="BN" type="xs:string" ></xs:attribute>
									<xs:attribute name="AR" type="xs:string" ></xs:attribute>
									<xs:attribute name="RU" type="xs:string" ></xs:attribute>
									<xs:attribute name="HI_IN" type="xs:string" ></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string"/>
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="CQL" type="xs:string" />
									<xs:attribute name="cqlcols" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="style" type="xs:string" /> 
									<xs:attribute name="overlaystreamlines" type="xs:string" /> 
									<xs:attribute name="defParticleSpeed" type="xs:string" /> 
									<xs:attribute name="max_time_range">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="week" /> 
												<xs:enumeration value="month" />
												<xs:enumeration value="year" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
                                    <xs:attribute name="zoom" type="xs:string" />
                                    <xs:attribute name="center" type="xs:string" />
                                </xs:complexType>
                  
							</xs:element><!-- End of Menuconf/MainLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of MainLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="cqlcols" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="style" type="xs:string" />  
						<xs:attribute name="selected">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="max_time_range">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="week" /> 
									<xs:enumeration value="month" />
									<xs:enumeration value="bimonth" />
									<xs:enumeration value="year" />                                                           
								</xs:restriction> 
							</xs:simpleType>
                    </xs:attribute>
					</xs:complexType>
				</xs:element> <!--End of MainLayer -->
   
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- end of root element -->

</xs:schema>

=== olmozavala/OWGIS/src/main/webapp/layers/TestLayers.xml
<MenuConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<!-- This are the menus that are available to display entries -->
	<Menus>
		<Menu ID="lev1" EN="Level 1" ES="Nivel 1" HI_IN="स्तर १"/>
		<Menu ID="vectest" EN="Vector layer" ES="Ejemplo Vectorial" HI_IN="वेक्टर परत"/>
		<Menu ID="veccqltest" EN="Vector CQL demo" ES="Ejemplo CQL" HI_IN="वेक्टर CQL"/>
		<Menu ID="geotifftest" EN="Raster (GeoTIFF)" ES="Ejemplo capa raster " HI_IN="रेस्टर (geotiff)"/>
		<Menu ID="vector" EN="Vector Layers" ES="Vectoriales" HI_IN="वेक्टर परते"/>
		<Menu ID="raster" EN="Raster Layers" ES="Capas Raster" HI_IN="वेक्टर परते"/>
		<Menu ID="states" EN="US states" ES="Estados" HI_IN="अमेरिकन राज्यों"/>
		<Menu ID="statesdyn" EN="Dynamic US states" ES="Estados (dinamicos)" HI_IN="अमेरिकन राज्यों"/> 
                <Menu ID="countries" EN="Countries" ES="Paises" HI_IN="देशों"/> 
                <Menu ID="count" EN="Countries" ES="Paises" HI_IN="देशों"/> 
	</Menus>

    <!-- GEBCO LAYER working properly but slow and heavy Jun/2017 -->
	<!-- 
	<BackgroundLayers server="http://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv"
				BBOX="-180,90,-90,180" > 
			<layer name="GEBCO_LATEST" featureInfo="none"/> 
	</BackgroundLayers>-->
	<!--CHECK THIS ONE http://demo.opengeo.org/geoserver/wms?request=GetCapabilities-->
	<BackgroundLayers BBOX="-180,-90,180,90" server="http://132.248.8.238:8080/geoservercenapred/wms">
		<layer name="cen:pyrResult512" /> 
	</BackgroundLayers>

	<!-- Vector layer -->
	<MainLayers BBOX="-175.22056447761656,-41.29997393927641,179.21664709402887,64.15002361973922"
				server="http://132.248.8.238:8080/geoserver/wms"
				vectorLayer="true">
		<layer Menu='vector,vectest' EN='Vector layer demo. World big cities. ' 
			   ES='Ejemplo de una capa vectorial. Grandes ciudades del mundo' HI_IN='वेक्टर परते का प्रदर्शन. दुनिया के बड़े शहरों.' name='demo:world_cities' />
	</MainLayers>

	<!-- Vector CQL layer -->
	<MainLayers BBOX="-175.22056447761656,-41.29997393927641,179.21664709402887,64.15002361973922"
				server="http://132.248.8.238:8080/geoserver/wms"
				vectorLayer="true"
				cqlcols="NAME">
		<layer Menu="vector,veccqltest" name="demo:world_cities" 
			   EN="Demo CQL filtering. Estimated population in 2010 more 2 million" 
			   ES="Ejemplo de filtrado con CQL. Grandes ciudades con mas de 2 millones de personas en 2010"
			   HI_IN="CQL फ़िल्टरिंग का प्रदर्शन. अनुमानित जनसंख्या वर्ष २०१०  में २०  लाख से अधिक" zoom="1" center="-100,22"
			   CQL="MAX_POP10 > 2000000" />
	</MainLayers>

	<!-- GeotiffLayer -->
	<MainLayers BBOX="-125.0,4.999999999999975,-75.00000000000003,35.0"
				server="http://132.248.8.238:8080/geoserver/wms">
		<layer Menu="raster,geotifftest" 
			   EN="Demo of a raster (GeoTIFF) layer. Maximum average temperature of July month." 
			   ES="Ejemplo de capa raster (GeoTIFF). Temperatura maxima promedio del mes de julio." 
			   HI_IN="रेस्टर (geotiff) परत का प्रदर्शन. जुलाई माह का अधिकतम औसत तापमान"
			   name="demo:temp_max_mex"/>
	</MainLayers>
</MenuConf>

=== olmozavala/OWGIS/src/main/webapp/layers/WRFLayers_AirQuality.xml
<MenuConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<!-- This are the menus that are available to display entries -->
	<Menus>
		<Menu ID="AIRQ" EN="Air quality (Mex)" ES="Calidad del aire"/>
		<Menu ID="Viento" EN="Wind" ES="Viento" />
		<Menu ID="VarViento" EN=" With Wind" ES="Variables con Viento" />
		<Menu ID="VarSinViento" EN=" Without Wind" ES="Variables sin Viento" />
		<Menu ID="VtoSup10" EN="Wind speed at 10 meters" ES="Viento a 10 metros"/>
		<Menu ID="Temp2" EN="Temperature at 2 meters" ES="Temperatura a 2 metros"/>
		<Menu ID="Pblh" EN="PBLH" ES="PBLH"/>
		<Menu ID="co" EN="CO" ES="CO"/> 
		<Menu ID="o3" EN="O3" ES="O3"/>
		<Menu ID="PM10" EN="PM10" ES="PM10"/>
		<Menu ID="del" EN="del" ES="del"/>
		<Menu ID="flip" EN="flip" ES="flip"/>
                
                <Menu ID="so2" EN="SO2" ES="SO2" />
                <Menu ID="nox" EN="NOX" ES="NOX" />
		<!-- Tais menu that are available to display entries IOA OWGIS-->
	</Menus>
        <!-- Dominio 1 -->
	<MainLayers BBOX="-122.25056107685108,7.409418707415154,-74.74943892314892,36.11315809004144" format="image/gif" server="http://132.248.8.238:8080/ncWMS_2015/wms" ncWMStwo="true" >
		<!-- variables con viento -->
		<layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarViento,Temp2" isParticle="false" overlaystreamlines="wrf-chem/Uat10:wrf-chem/Vat10" defParticleSpeed="0.03" EN="Temperature at 2 meters." ES="Temperatura en superficie a 2 metros" style="default-scalar" palette="temperatura" name="wrf-chem/T2C" mincolor="-10" maxcolor="50" />

		<layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarViento,co" isParticle="co" overlaystreamlines="wrf-chem/Uat10:wrf-chem/Vat10" defParticleSpeed="0.03" EN="CO (ppm)" ES="CO (ppm)" style="default-scalar" palette="div-Spectral-inv" name="wrf-chem/co" mincolor="0" maxcolor="2" aboveMaxColor="transparent" belowMinColor="transparent" />

		<layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarViento,o3" isParticle="otres" overlaystreamlines="wrf-chem/Uat10:wrf-chem/Vat10" defParticleSpeed="0.03" EN="O3 (ppm)" ES="O3 (ppm)" style="default-scalar" palette="div-Spectral-inv" name="wrf-chem/o3" mincolor="0" maxcolor="160" aboveMaxColor="transparent" belowMinColor="transparent" />

		<layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarViento,PM10" isParticle="pmdiez" overlaystreamlines="wrf-chem/Uat10:wrf-chem/Vat10" defParticleSpeed="0.03" EN="PM10 (ug m^-3)" ES="PM10 (ug m^-3)" style="default-scalar" palette="seq-PuBuGn-inv" name="wrf-chem/PM10" mincolor="0" maxcolor="100" aboveMaxColor="transparent" belowMinColor="transparent" />

		<layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarViento,so2" isParticle="sodos" overlaystreamlines="wrf-chem/Uat10:wrf-chem/Vat10" defParticleSpeed="0.03" EN="so2 (ppm)" ES="so2 (ppm)" style="default-scalar" palette="seq-Heat-inv" name="wrf-chem/so2" mincolor="0" maxcolor="50" aboveMaxColor="transparent" belowMinColor="transparent" />

		<layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarViento,nox" isParticle="nox" overlaystreamlines="wrf-chem/Uat10:wrf-chem/Vat10" defParticleSpeed="0.03" EN="nox (ppm)" ES="nox (ppm)" style="default-scalar" palette="seq-BlueHeat-inv" name="wrf-chem/NOX" mincolor="0" maxcolor="30" aboveMaxColor="transparent" belowMinColor="transparent" />

		<layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,o3" EN="O3 (ppm)" ES="O3 (ppm)" isParticle="otres" style="default-scalar"
				   palette="div-Spectral-inv" name="wrf-chem/o3" mincolor="0" maxcolor="160" aboveMaxColor="transparent" belowMinColor="transparent" />

		<!-- variables sin viento -->
            <layer  center="-99,19" zoom="4" isParticle="false" Menu="AIRQ,Dom2,VarSinViento,Temp2" EN="Temperature at 2 meters."
				   ES="Temperatura en superficie a 2 metros" style="default-scalar" palette="temperatura" name="wrf-chem/T2C" mincolor="-10" maxcolor="50" />
            
            <layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarSinViento,VtoSup10" EN="Wind speed at 10 meters" ES="Viento a 10 metros"
                    style="default-scalar" palette="wind2" name="wrf-chem/Uat10:Vat10-mag"
                    overlaystreamlines="wrf-chem/Uat10:wrf-chem/Vat10" defParticleSpeed="0.03"  mincolor="0" maxcolor="250" isParticle="false" />

            <layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarSinViento,Pblh" EN="Planetary boundary layer height" isParticle="false"
				   ES="Altura de la capa lÃ­mite planetaria" style="default-scalar" palette="prec2" name="wrf-chem/PBLH" mincolor="-170" maxcolor="3770" />
                
            <layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarSinViento,co" EN="CO (ppm)" ES="CO (ppm)" isParticle="co" style="default-scalar"
				   palette="div-Spectral-inv" name="wrf-chem/co" mincolor="0" maxcolor="2" aboveMaxColor="transparent" belowMinColor="transparent" />


            <layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarSinViento,PM10" EN="PM10 (ug m^-3)" ES="PM10 (ug m^-3)" isParticle="pmdiez"
				   style="default-scalar" palette="seq-PuBuGn-inv" name="wrf-chem/PM10" mincolor="0" maxcolor="100" aboveMaxColor="transparent" belowMinColor="transparent" />

            <layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarSinViento,so2" EN="so2 (ppm)" ES="so2 (ppm)" isParticle="sodos" style="default-scalar"
				   palette="seq-Heat-inv" name="wrf-chem/so2" mincolor="0" maxcolor="50" aboveMaxColor="transparent" belowMinColor="transparent" />
            
            <layer  center="-99,19" zoom="4" Menu="AIRQ,Dom2,VarSinViento,nox" EN="nox (ppm)" ES="nox (ppm)" isParticle="nox" style="default-scalar"
				   palette="seq-BlueHeat-inv" name="wrf-chem/NOX" mincolor="0" maxcolor="30" aboveMaxColor="transparent" belowMinColor="transparent" />
	</MainLayers>
</MenuConf>
