=== olmozavala/OWGIS/src/main/webapp/layers/schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="MenuConf"><!-- root element-->
  
		<xs:complexType mixed="true">
			<xs:sequence maxOccurs="unbounded"><!--childs of root, limited to 3 for now -->    
   
				<xs:element name="Menus" minOccurs="0"><!--Menus(root's child) level -->
					<xs:complexType mixed="true">
  
						<xs:sequence maxOccurs="unbounded"><!--infinite limit of MenuEntry numbers -->
      
							<xs:element name="MenuEntry" minOccurs="1"> <!--MenuEntry level -->
								<xs:complexType mixed="true">          
									<xs:attribute name="ID" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="EN" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="ES" type="xs:string" ></xs:attribute>
									<xs:attribute name="FR" type="xs:string" ></xs:attribute>
									<xs:attribute name="MS" type="xs:string" ></xs:attribute>
									<xs:attribute name="PT" type="xs:string" ></xs:attribute>
									<xs:attribute name="BN" type="xs:string" ></xs:attribute>
									<xs:attribute name="AR" type="xs:string" ></xs:attribute>
									<xs:attribute name="RU" type="xs:string" ></xs:attribute>
									<xs:attribute name="HI_IN" type="xs:string" ></xs:attribute>
									<!-- For validating other languages is necessary to add them here -->
								</xs:complexType>                 
							</xs:element>       
						</xs:sequence>  
					</xs:complexType>
				</xs:element><!--end of Menus -->
   
				<xs:element name="BackgroundLayers" minOccurs="0"> <!--BackgroundLayers (root's child) level -->
       
					<xs:complexType mixed="true">
						<!--different optional atributes of background layer -->
       
						<xs:sequence maxOccurs="unbounded">
       
							<xs:element name="layer" minOccurs="1"> <!--Menuconf/BackgroundLayers/layer -->
								<xs:complexType mixed="true">
          
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string" />
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="style" type="xs:string" /> 
								</xs:complexType>
                  
							</xs:element><!-- End of Menuconf/BackgroundLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of BackgroundLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      

						<xs:attribute name="style" type="xs:string" />  
					</xs:complexType>
				</xs:element> <!--End of BackgroundLayer -->
   
				<xs:element name="OptionalLayers" minOccurs="0"> <!--OptionalLayers (root's child) level -->
       
					<xs:complexType mixed="true">
						<xs:sequence maxOccurs="unbounded">
       
							<xs:element name="layer" minOccurs="1"> <!--Menuconf/BackgroundLayers/layer -->
								<xs:complexType mixed="true">
          
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="Menu" type="xs:string"></xs:attribute>
									<xs:attribute name="featureInfo" type="xs:string"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string" />
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="selected">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      

									<xs:attribute name="style" type="xs:string" /> 
								</xs:complexType>
                  
							</xs:element><!-- End of Menuconf/OptionalLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of OptionalLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      

						<xs:attribute name="style" type="xs:string" />
                        <xs:attribute name="zoom" type="xs:string" />
                        <xs:attribute name="center" type="xs:string" />  
					</xs:complexType>
				</xs:element> <!--End of OptionalLayers -->
   
   
				<xs:element name="MainLayers" minOccurs="0"> <!--MainLayers (root's child) level -->
					<xs:complexType mixed="true">
						<xs:sequence maxOccurs="unbounded"><!-- There can be multiple MainLayers element on the xml file -->
							<xs:element name="layer" minOccurs="1"> <!--Internal element of Main layers is a layer -->
								<xs:complexType mixed="true">
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="Menu" type="xs:string"></xs:attribute>
									<xs:attribute name="featureInfo" type="xs:string"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="EN" type="xs:string"></xs:attribute>
									<xs:attribute name="ES" type="xs:string" ></xs:attribute>
									<xs:attribute name="FR" type="xs:string" ></xs:attribute>
									<xs:attribute name="MS" type="xs:string" ></xs:attribute>
									<xs:attribute name="PT" type="xs:string" ></xs:attribute>
									<xs:attribute name="BN" type="xs:string" ></xs:attribute>
									<xs:attribute name="AR" type="xs:string" ></xs:attribute>
									<xs:attribute name="RU" type="xs:string" ></xs:attribute>
									<xs:attribute name="HI_IN" type="xs:string" ></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string"/>
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="CQL" type="xs:string" />
									<xs:attribute name="cqlcols" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="style" type="xs:string" /> 
									<xs:attribute name="overlaystreamlines" type="xs:string" /> 
									<xs:attribute name="defParticleSpeed" type="xs:string" /> 
									<xs:attribute name="max_time_range">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="week" /> 
												<xs:enumeration value="month" />
												<xs:enumeration value="year" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
                                    <xs:attribute name="zoom" type="xs:string" />
                                    <xs:attribute name="center" type="xs:string" />
                                </xs:complexType>
                  
							</xs:element><!-- End of Menuconf/MainLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of MainLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="cqlcols" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="style" type="xs:string" />  
						<xs:attribute name="selected">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="max_time_range">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="week" /> 
									<xs:enumeration value="month" />
									<xs:enumeration value="bimonth" />
									<xs:enumeration value="year" />                                                           
								</xs:restriction> 
							</xs:simpleType>
                    </xs:attribute>
					</xs:complexType>
				</xs:element> <!--End of MainLayer -->
   
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- end of root element -->

</xs:schema>

=== olmozavala/OWGIS/src/main/webapp/layers/GFS_and_HYCOM_Forecasts.xml
<MenuConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<!-- This are the menus that are available to display entries -->
	<Menus>
		<Menu ID="hycom" EN="HYCOM" ES="HYCOM"/>
		<Menu ID="GLBL" EN="Global Weather" ES="Global"/>
		<Menu ID="gfs" EN="GFS" ES="GFS"/>

		<Menu ID="abvgrnd"  EN="Above Ground" ES="Sobre Tierra" />
		<Menu ID="grnd"  EN="Ground" ES="En Tierra" />
		<Menu ID="geo"  EN="Geo Potential H." ES="Altura Geopot." />
		<Menu ID="cur"  EN="Currents" ES="Corrientes" />
		<Menu ID="cld"  EN="Cloud" ES="Nubes" />
		<Menu ID="ccov"  EN="Cloud Cover" ES="Covertura Nubes" />
		<Menu ID="conv"  EN="Potential Energy" ES="Energia Potencial" />
		<Menu ID="hum"  EN="Humidity" ES="Humedad" />
		<Menu ID="isobar"  EN="Isobaric" ES="Isobarica" />
		<Menu ID="msl"  EN="MSL" ES="MSL" />
		<Menu ID="ozone"  EN="Total Ozone" ES="Ozono Total" />
		<Menu ID="prec"  EN="Prec. Water" ES="Agua Prec" />
		<Menu ID="pres"  EN="Pressure" ES="Presion" />
		<Menu ID="plan"  EN="Planetary Height" ES="Altura Planetaria" />
		<Menu ID="surf"  EN="At Surface" ES="En Superficie" />
		<Menu ID="suri"  EN="Surface lifted idx." ES="Indice superficial" />
		<Menu ID="sun"  EN="Sunshine time" ES="Duracion sol" />
		<Menu ID="sal"  EN="Salinity" ES="Salinidad" />
		<Menu ID="ssh"  EN="Elevation" ES="Altura" />
		<Menu ID="tic"  EN="Ice Cover" ES="Hielo" />
		<Menu ID="twom"  EN="Two Meters" ES="A 2 metros" />
		<Menu ID="ts"  EN="Temperature" ES="Temperatura" />
		<Menu ID="wind"  EN="Wind" ES="Viento" />
		<Menu ID="vor"  EN="Vorticity" ES="Vorticidad" />
	</Menus>
        <!--HYCOM-->
	<MainLayers BBOX="-180,-90,180,90"
				format="image/gif"  server="http://132.248.8.238:8080/ncWMS_2015/wms"
				ncWMStwo="true" max_time_range="month">  

		<layer Menu="GLBL,hycom,cur" 
			   EN="Forecast currents"
			   name="hycom_forecast_uv/water_u:water_v-mag" 
			   defParticleSpeed=".9" overlaystreamlines="hycom_forecast_uv/water_u:hycom_forecast_uv/water_v" />

		<layer Menu="GLBL,hycom,ts" 
			   EN="Forecast temperature" 
			   name="hycom_forecast_ts/water_temp" 
                           palette="div-Spectral-inv"
			   defParticleSpeed=".9" overlaystreamlines="hycom_forecast_uv/water_u:hycom_forecast_uv/water_v" />

		<layer Menu="GLBL,hycom,sal" 
			   EN="Forecast salinity"
			   name="hycom_forecast_ts/salinity" 
			   defParticleSpeed=".9" overlaystreamlines="hycom_forecast_uv/water_u:hycom_forecast_uv/water_v" />

		<layer Menu="GLBL,hycom,ssh" 
			   EN="Forecast sea surface height"
			   name="hycom_forecast_ssh/surf_el" 
                           palette="adcirc"
			   defParticleSpeed=".9" overlaystreamlines="hycom_forecast_uv/water_u:hycom_forecast_uv/water_v" />

		<!--
		<layer Menu="GLBL,gfs,wind,abvgrnd" EN="Wind above ground" ES="Viento en superficie"
			   name="gfs_forecast/v_abvgrd:u_abvgrd-mag" defParticleSpeed=".05"  mincolor="0" maxcolor="70" belowMinColor="transparent" aboveMaxColor="transparent"
			   overlaystreamlines="gfs_forecast/v_abvgrd:gfs_forecast/u_abvgrd" palette="wind2"  />

		<layer Menu="GLBL,gfs,wind,isobar" EN="Isobaric wind" ES="Viento isobárico" 
			   name="gfs_forecast/v_isobar:u_isobar-mag" defParticleSpeed=".010" mincolor="0" maxcolor="70" belowMinColor="transparent" aboveMaxColor="transparent"
			   overlaystreamlines="gfs_forecast/v_isobar:gfs_forecast/u_isobar" palette="wind2" />
                
                <layer Menu="GLBL,gfs,ts,surf" EN="Surface temperature" mincolor="-40" maxcolor="50"
			   ES="Temperatura en superficie" name="gfs_forecast/temp_surf" palette="div-Spectral-inv" />
                
                
	   <layer Menu="GLBL,gfs,ts,abvgrnd" EN="Temperature above ground" palette="div-Spectral-inv" mincolor="-40" maxcolor="50"
			  ES="Temperatura sobre superficie" name="gfs_forecast/temp_abvgrd" />
           
	   <layer Menu="GLBL,gfs,ts,isobar" EN="Isobaric temperature" palette="div-Spectral-inv" mincolor="-40" maxcolor="50"
			  ES="Temperatura isobarica" name="gfs_forecast/temp_isobar" />
	   
           <layer Menu="GLBL,gfs,hum,twom" EN="Humidity at 2 mts" palette="prec" mincolor="0" maxcolor="100"  belowMinColor="transparent" aboveMaxColor="transparent"
			  ES="Humedad a 2 mts" name="gfs_forecast/humidity_twom" />
           
	   <layer Menu="GLBL,gfs,hum,isobar" EN="Isobaric humidity" palette="prec" mincolor="0" maxcolor="100"  belowMinColor="transparent" aboveMaxColor="transparent"
			  ES="Humedad isobarica" name="gfs_forecast/humidity_isobar" />
           
           <layer Menu="GLBL,gfs,prec" EN="Precipitation" 
			  ES="Precipitación" name="gfs_forecast/prec_water" palette="prec2" mincolor="1" maxcolor="400" />
           
           <layer Menu="GLBL,gfs,vor" EN="Vorticity" mincolor="-0.00001" maxcolor="0.001" belowMinColor="0x000000" aboveMaxColor="0xFFFFFF"
			  ES="Vorticidad" name="gfs_forecast/abs_vort" />
           
           <layer Menu="GLBL,gfs,pres,grnd" EN="Ground pressure"
			  ES="Presión" name="gfs_forecast/pres_grd" mincolor="47020" maxcolor="106300" />
           <layer Menu="GLBL,gfs,pres,msl" EN="MSL pressure"
			  ES="Presión MSL" name="gfs_forecast/pres_msl" mincolor="94260" maxcolor="105000" />
           
           <layer Menu="GLBL,gfs,geo" EN="Geo potential height" 
			  ES="Altura geo potencial "
			  name="gfs_forecast/geo_height_isobar" mincolor="-328" maxcolor="392" />
           
           <layer Menu="GLBL,gfs,plan" EN="Planetary height"
			  ES="Altura planetaria" name="gfs_forecast/plan_height" mincolor="-200" maxcolor="3630" />
           <layer Menu="GLBL,gfs,conv" EN="Potential energy"
			  ES="Energía potencial" name="gfs_forecast/conv_en" mincolor="-200" maxcolor="4150" />
	   <layer Menu="GLBL,gfs,suri" EN="Surface lifted index"
			  name="gfs_forecast/surf_idx" mincolor="-13" maxcolor="50" />
           
	   <layer Menu="GLBL,gfs,ozone" EN="Total ozone"  belowMinColor="0x000000" aboveMaxColor="0xFFFFFF"
			  ES="Ozono total" name="gfs_forecast/tot_ozone" mincolor="100" maxcolor="500" />
           
	   <layer Menu="GLBL,gfs,tic" EN="Ice cover"
			  ES="Hielo" name="gfs_forecast/tot_ice_cov" mincolor="-1" maxcolor="1.5" />
	   <layer Menu="GLBL,gfs,sun" EN="Sunshine time"
			  ES="Tiempo de sol" name="gfs_forecast/sun_dur" mincolor="-1079" maxcolor="22680" />

		-->
	</MainLayers> 
</MenuConf>
