=== olmozavala/OWGIS/src/main/webapp/layers/schema.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="MenuConf"><!-- root element-->
  
		<xs:complexType mixed="true">
			<xs:sequence maxOccurs="unbounded"><!--childs of root, limited to 3 for now -->    
   
				<xs:element name="Menus" minOccurs="0"><!--Menus(root's child) level -->
					<xs:complexType mixed="true">
  
						<xs:sequence maxOccurs="unbounded"><!--infinite limit of MenuEntry numbers -->
      
							<xs:element name="MenuEntry" minOccurs="1"> <!--MenuEntry level -->
								<xs:complexType mixed="true">          
									<xs:attribute name="ID" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="EN" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="ES" type="xs:string" ></xs:attribute>
									<xs:attribute name="FR" type="xs:string" ></xs:attribute>
									<xs:attribute name="MS" type="xs:string" ></xs:attribute>
									<xs:attribute name="PT" type="xs:string" ></xs:attribute>
									<xs:attribute name="BN" type="xs:string" ></xs:attribute>
									<xs:attribute name="AR" type="xs:string" ></xs:attribute>
									<xs:attribute name="RU" type="xs:string" ></xs:attribute>
									<xs:attribute name="HI_IN" type="xs:string" ></xs:attribute>
									<!-- For validating other languages is necessary to add them here -->
								</xs:complexType>                 
							</xs:element>       
						</xs:sequence>  
					</xs:complexType>
				</xs:element><!--end of Menus -->
   
				<xs:element name="BackgroundLayers" minOccurs="0"> <!--BackgroundLayers (root's child) level -->
       
					<xs:complexType mixed="true">
						<!--different optional atributes of background layer -->
       
						<xs:sequence maxOccurs="unbounded">
       
							<xs:element name="layer" minOccurs="1"> <!--Menuconf/BackgroundLayers/layer -->
								<xs:complexType mixed="true">
          
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string" />
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="style" type="xs:string" /> 
								</xs:complexType>
                  
							</xs:element><!-- End of Menuconf/BackgroundLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of BackgroundLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      

						<xs:attribute name="style" type="xs:string" />  
					</xs:complexType>
				</xs:element> <!--End of BackgroundLayer -->
   
				<xs:element name="OptionalLayers" minOccurs="0"> <!--OptionalLayers (root's child) level -->
       
					<xs:complexType mixed="true">
						<xs:sequence maxOccurs="unbounded">
       
							<xs:element name="layer" minOccurs="1"> <!--Menuconf/BackgroundLayers/layer -->
								<xs:complexType mixed="true">
          
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="Menu" type="xs:string"></xs:attribute>
									<xs:attribute name="featureInfo" type="xs:string"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string" />
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="selected">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      

									<xs:attribute name="style" type="xs:string" /> 
								</xs:complexType>
                  
							</xs:element><!-- End of Menuconf/OptionalLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of OptionalLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      

						<xs:attribute name="style" type="xs:string" />
                        <xs:attribute name="zoom" type="xs:string" />
                        <xs:attribute name="center" type="xs:string" />  
					</xs:complexType>
				</xs:element> <!--End of OptionalLayers -->
   
   
				<xs:element name="MainLayers" minOccurs="0"> <!--MainLayers (root's child) level -->
					<xs:complexType mixed="true">
						<xs:sequence maxOccurs="unbounded"><!-- There can be multiple MainLayers element on the xml file -->
							<xs:element name="layer" minOccurs="1"> <!--Internal element of Main layers is a layer -->
								<xs:complexType mixed="true">
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="Menu" type="xs:string"></xs:attribute>
									<xs:attribute name="featureInfo" type="xs:string"></xs:attribute>
									<xs:attribute name="title" type="xs:string"></xs:attribute>
									<xs:attribute name="EN" type="xs:string"></xs:attribute>
									<xs:attribute name="ES" type="xs:string" ></xs:attribute>
									<xs:attribute name="FR" type="xs:string" ></xs:attribute>
									<xs:attribute name="MS" type="xs:string" ></xs:attribute>
									<xs:attribute name="PT" type="xs:string" ></xs:attribute>
									<xs:attribute name="BN" type="xs:string" ></xs:attribute>
									<xs:attribute name="AR" type="xs:string" ></xs:attribute>
									<xs:attribute name="RU" type="xs:string" ></xs:attribute>
									<xs:attribute name="HI_IN" type="xs:string" ></xs:attribute>
									<xs:attribute name="BBOX" type="xs:string"/>
									<xs:attribute name="vectorLayer">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="format" type="xs:string" />
									<xs:attribute name="proj" type="xs:string" />
									<xs:attribute name="server" type="xs:string" />
									<xs:attribute name="palette" type="xs:string" />
									<xs:attribute name="trans_effect" type="xs:string" />
									<xs:attribute name="width" type="xs:string" />
									<xs:attribute name="height" type="xs:string" />
									<xs:attribute name="mincolor" type="xs:string" />
									<xs:attribute name="CQL" type="xs:string" />
									<xs:attribute name="cqlcols" type="xs:string" />
									<xs:attribute name="maxcolor" type="xs:string" />
									<xs:attribute name="tiled">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMS">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="ncWMStwo">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="true" /> 
												<xs:enumeration value="false" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
									<xs:attribute name="style" type="xs:string" /> 
									<xs:attribute name="overlaystreamlines" type="xs:string" /> 
									<xs:attribute name="defParticleSpeed" type="xs:string" /> 
									<xs:attribute name="max_time_range">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="week" /> 
												<xs:enumeration value="month" />
												<xs:enumeration value="year" />                                                           
											</xs:restriction> 
										</xs:simpleType>
									</xs:attribute>                      
                                    <xs:attribute name="zoom" type="xs:string" />
                                    <xs:attribute name="center" type="xs:string" />
                                </xs:complexType>
                  
							</xs:element><!-- End of Menuconf/MainLayers/layer -->
       
						</xs:sequence>
						<!-- Attributes of MainLayers -->
						<xs:attribute name="BBOX" type="xs:string" />
						<xs:attribute name="vectorLayer">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="format" type="xs:string" />
						<xs:attribute name="proj" type="xs:string" />
						<xs:attribute name="server" type="xs:string" />
						<xs:attribute name="palette" type="xs:string" />
						<xs:attribute name="trans_effect" type="xs:string" />
						<xs:attribute name="width" type="xs:string" />
						<xs:attribute name="height" type="xs:string" />
						<xs:attribute name="cqlcols" type="xs:string" />
						<xs:attribute name="mincolor" type="xs:string" />
						<xs:attribute name="maxcolor" type="xs:string" />
						<xs:attribute name="tiled">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                     
						<xs:attribute name="ncWMS">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute> 
						<xs:attribute name="ncWMStwo">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="style" type="xs:string" />  
						<xs:attribute name="selected">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="true" /> 
									<xs:enumeration value="false" />                                                           
								</xs:restriction> 
							</xs:simpleType>
						</xs:attribute>                      
						<xs:attribute name="max_time_range">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="week" /> 
									<xs:enumeration value="month" />
									<xs:enumeration value="bimonth" />
									<xs:enumeration value="year" />                                                           
								</xs:restriction> 
							</xs:simpleType>
                    </xs:attribute>
					</xs:complexType>
				</xs:element> <!--End of MainLayer -->
   
			</xs:sequence>
		</xs:complexType>
	</xs:element><!-- end of root element -->

</xs:schema>

=== olmozavala/OWGIS/src/main/webapp/layers/1_NCWMS_Layers.xml
<MenuConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<!-- This are the menus that are available to display entries -->
	<Menus>
		<Menu ID="EXS" EN="Examples" ES="Ejemplos" HI_IN="Examples"/>
		<Menu ID="ncwms" EN="ncWMS Layers" ES="Capas ncWMS" HI_IN="ncWMS परते"/>
		<Menu ID="ncwmsOneDateMultZ" EN="ncWMS MultZ OneDate" ES="ESP ncWMS MultZ OneDate"/>
		<Menu ID="ncwmsOneDepthOneZ" EN="ncWMS OneZ OneDate " ES="ESP ncWMS OneZ OneDate "/>
		<Menu ID="ncwmvelocity" EN="ncWMS MultZ MultDate" ES="ESP ncWMS MultZ MultDates"/>
		<Menu ID="ncwmsMultDateMultDepth" EN="ncWMS MultZ MultDate" ES="ESP ncWMS MultZ MultDate"/>
		<Menu ID="worldTempCurrents" EN="World Temperature w Currents " ES="Temperatura y corrientes"/>
		<Menu ID="worldCurrents" EN="World Currents " ES="Corrientes Tierra"/>
		<Menu ID="ncwmsMultTimes" EN="ncWMS MultTimes" ES="ESP ncWMS MultTimes"/>
		<Menu ID="oldncwms" EN="ncWMS V1" ES="ESP ncWMS V1"/>
	</Menus>

	<MainLayers BBOX="-98.0,18.09164810180664,-76.400024,31.960647583007812" 
				format="image/gif"  server="http://132.248.8.238:8080/ncWMS_2015/wms"
				 ncWMStwo="true" >  

	<!-- ncWMS  World temperatures with currents and currents -->
		<layer Menu="EXS,ncwms,worldTempCurrents" 
			   EN="Gulf of Mexico Temperatures and currents"
			   defParticleSpeed=".9"
			   name="global_ts_2015/water_temp" 
			   style="default-scalar" palette="wind2"
			   overlaystreamlines="global_uv_2015/water_u:global_uv_2015/water_v" />

		<layer Menu="EXS,ncwms,worldCurrents" 
			   EN="World Currents"
			   name="hycom_forecast_uv/water_u:water_v-mag" 
			   defParticleSpeed=".9"
			   overlaystreamlines="hycom_forecast_uv/water_u:hycom_forecast_uv/water_v" />


		<!-- ncWMS with one date multiple Z-->
		<layer Menu="EXS,ncwms,ncwmsOneDateMultZ" 
			   EN="Demo of an ncWMS layer with only one day. World eastward wind."
			   ES="Ejemplo de una capa ncWMS con multiples z-axis. Vientos hacia el este." 
			   HI_IN="केवल एक दिन का ncWMS परत प्रदर्शन. दुनिया के पूर्व की ओर हवा"
			   name="world_temp/ua"  />

		<!-- ncWMS with one depth-->
		<layer Menu="EXS,ncwms,ncwmsOneDepthOneZ" 
			   EN="Demo of an ncWMS layer with only one depth. World precipitation flux."
			   ES="Ejemplo de una capa ncWMS con solo una elevacion. Flujo de precipitacion." 
			   HI_IN="केवल एक ही गहराई के साथ ncWMS परत का प्रदर्शन. दुनिया की तेज़ी प्रवाह"
			   name="world_temp/pr"  />

		<!-- ncWMS mulitple Z multiple date/ velocity-->
		<layer Menu="EXS,ncwms,ncwmvelocity" EN="Demo of an ncWMS velocity layer. Ocean currents of the Gulf of Mexico" 
			   ES="Ejemplo de una capa de velocidad de servidor ncWMS. Velocidad de corrientes del Gulfo de Mexico" 
			   HI_IN="ncWMS गति परत का प्रदर्शन. मैक्सिको की खाड़ी के समुद्र धाराओं"
			   name="gulf_vel/u:v-mag" 
				ncWMStwo="true"
				style="default-scalar" palette="default" />
			   <!--overlaystreamlines="gulf_vel/u:gulf_vel/v" />-->
			   <!--style="default-scalar | colored-contours | contours | raster "-->

		<!-- ncWMS mulitple Z multiple date multip time/ temperature-->
		<layer Menu="EXS,ncwms,ncwmvelocity" EN="Demo of an ncWMS temperature layer. " 
			   ES="Ejemplo de una capa de temperatura de servidor ncWMS 2" 
			   name="gulf_vel/u:v-mag" 
				ncWMStwo="true"   
			   style="default-scalar" palette="default" />

		<!--
	   <layer Menu="EXS,ncwms,ncwmsMultTimes" EN="Surface temperature" 
			   ES="Temperatura en superficie" name="gfs_forecast/temp_surf" /> -->
	</MainLayers>

<!--    <MainLayers BBOX="-98.0,18.09164810180664,-76.400024,31.960647583007812" -->
<!--                format="image/png"  server="http://ncwms.coaps.fsu.edu/ncWMS/wms"-->
<!--                tiled="true" ncWMS="true" mincolor="10" maxcolor="34" max_time_range="month">  -->
<!--        <layer Menu="EXS,ncwms,oldncwms" EN="HYCOM " ES="HYCOM + " name="hycom2010/temperature"   />-->
<!--    </MainLayers>-->

	<!-- ncWMS all -->
	<!--
	<MainLayers BBOX="-98.0,18.09164810180664,-76.400024,31.960647583007812" 
				format="image/gif"  server="http://132.248.8.238:8080/ncWMS_2015/wms"
				ncWMS="true" mincolor="10" maxcolor="34" max_time_range="month">  
		<layer Menu="ncwms,ncwmsMultDateMultDepth" EN="Gulf of Mexico Temperature 2014"
			   ES="Golfo de M&#233;xico Temperatura 2014" 
			   name="gulf_temp/temperature" 
			   HI_IN="वर्ष 2014 में मैक्सिको की खाड़ी का तापमान" />

	</MainLayers> 
	-->

</MenuConf>

=== olmozavala/OWGIS/src/main/webapp/layers/WWIIILayers.xml
<MenuConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<!-- This are the menus that are available to display entries -->
	<Menus>
		<Menu ID="WWIII" EN="Waves (Mex)" ES="Oleaje"/>
		<Menu ID="Wo" EN="World" ES="Global"/>
		<Menu ID="Viento" EN="Wind" ES="Viento" />
		<Menu ID="Altura" EN="Significant height" ES="Altura"/>
		<Menu ID="Periodo" EN="Mean period" ES="Periodo"/>
		
		<!-- Tais menu that are available to display entries IOA OWGIS-->
	</Menus>

	<!-- WWIII -->
	<MainLayers BBOX="-180,90,-90,180" format="image/gif" ncWMStwo="true"
                    server="http://132.248.8.238:8080/ncWMS_2015/wms" >
        
        <!--MainLayers BBOX="-180,90,-90,180" format="image/gif" ncWMStwo="true"
                    server="http://10.2.233.169:8080/ncWMS2/wms" -->
                   
		<layer Menu="WWIII,Pom,Altura" center="-101,23" zoom="3" EN="Significant wave height (m)" ES="Altura significante de oleaje (m)" 
                     name="wwiii_pom/hs" style="default-scalar" palette="alturamx" mincolor="0" maxcolor="12"
                     defParticleSpeed="0.03" overlaystreamlines="wwiii_pom/U:wwiii_pom/V" aboveMaxColor="transparent" belowMinColor="transparent"
                />                    
                
		<layer Menu="WWIII,Pom,Periodo" center="-101,23" zoom="3" EN="Period" ES="Periodo" 
			style="default-scalar" palette="periodo" name="wwiii_pom/t01" mincolor="1" maxcolor="22"
                        defParticleSpeed="0.03" overlaystreamlines="wwiii_pom/U:wwiii_pom/V" aboveMaxColor="transparent" belowMinColor="transparent"
                />
                   
		<layer Menu="WWIII,Gom,Altura" EN="Significant wave height (m)" ES="Altura significante de oleaje (m)"  center="-92,23" zoom="3"
                    style="default-scalar" palette="alturamx" name="wwiii_gom/hs" mincolor="0" maxcolor="12" aboveMaxColor="transparent" belowMinColor="transparent"
                    defParticleSpeed="0.03" overlaystreamlines="wwiii_gom/U:wwiii_gom/V"
                />                        
                
		<layer Menu="WWIII,Gom,Periodo" EN="Period" ES="Periodo" center="-92,23" zoom="3"
			style="default-scalar" palette="periodogo" name="wwiii_gom/t01" mincolor="0" maxcolor="13" aboveMaxColor="transparent" belowMinColor="transparent"
                        defParticleSpeed="0.03" overlaystreamlines="wwiii_gom/U:wwiii_gom/V"
                />
                   
		<layer Menu="WWIII,Wo,Altura" EN="Significant wave height (m)" ES="Altura significante de oleaje (m)" 
                    style="default-scalar" palette="oleaje" name="wwiii_wo/hs" mincolor="0" maxcolor="16" aboveMaxColor="transparent" belowMinColor="transparent"
                    defParticleSpeed="0.01" overlaystreamlines="wwiii_wo/U:wwiii_wo/V"
                />                          
                
		<layer Menu="WWIII,Wo,Periodo" EN="Period" ES="Periodo" mincolor="1" maxcolor="22" aboveMaxColor="transparent" belowMinColor="transparent"
			style="default-scalar" palette="periodo" name="wwiii_wo/t01"
                        defParticleSpeed="0.01" overlaystreamlines="wwiii_wo/U:wwiii_wo/V"
                />
                
	</MainLayers>

</MenuConf>

=== olmozavala/OWGIS/src/main/webapp/layers/WADCIRCLayers.xml
<MenuConf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
	<!-- This are the menus that are available to display entries -->
	<Menus>
		<Menu ID="ADCIRC" EN="Storm surge (Mex)" ES="Marea y tormenta"/>
		<Menu ID="Pom" EN="Pacific" ES="Pacífico"/>
		<Menu ID="Gom" EN="Gulf of Mexico" ES="Golfo de México"/>		
                <Menu ID="ele" EN="Elevation" ES="Elevación" />
	</Menus>
        
	<!-- ADCIRC -->
	<MainLayers BBOX="-122.25056107685108,7.409418707415154,-74.74943892314892,36.11315809004144" format="image/gif" 
                    server="http://132.248.8.238:8080/ncWMS_2015/wms" >
                   
		<layer Menu="ADCIRC,Pom,ele" EN="Water surface elevation above geoid (m)" ES="Elevación de la superficie del mar (m)"  center="-101,23" zoom="3"
                    name="adcir_pom/zeta" ncWMStwo="true" palette="adcirc" mincolor="-3.0" maxcolor="3.0" belowMinColor="transparent" aboveMaxColor="transparent"
                />
                     
		<layer Menu="ADCIRC,Gom,ele" EN="Water surface elevation above geoid (m)" ES="Elevación de la superficie del mar (m)" center="-92,23" zoom="3"
                    style="default-scalar" name="adcir_gom/zeta" ncWMStwo="true" palette="adcirc" mincolor="-3.0" maxcolor="3.0" belowMinColor="transparent" aboveMaxColor="transparent"
		/>                              
                
	</MainLayers>
</MenuConf>
